#!/usr/bin/env bash

set -euo pipefail

has_cmd() {
  command -v "$1" >/dev/null 2>&1
}

die() {
  printf "ERROR: %s\n" "$*" >&2
  exit 1
}

readonly REPO_URL="https://github.com/pervezfunctor/fedora-niri-config.git"
readonly DOT_DIR="$HOME/.local/share/fedora-niri-config"

dotfiles_install() {
  has_cmd git || die "git not found. Quitting."

  [ -d "$DOT_DIR" ] || {
    echo "Cloning dotfiles to $DOT_DIR."
    git clone "$REPO_URL" "$DOT_DIR" || die "Failed to clone $REPO_URL"
    return
  }

  [ -z "$(git -C "$DOT_DIR" status --porcelain)" ] && {
    echo "Dotfiles repo clean. Pulling latest changes"
    git -C "$DOT_DIR" pull --rebase || {
      echo "Rebase failed. Aborting."
      git -C "$DOT_DIR" rebase --abort || die "Failed to abort rebase"
    }
  }
}

system_install() {
  sudo dnf update -y || die "Failed to update packages"
  sudo dnf install -y git gcc pipx libatomic make plocate tar unzip zstd ||
    die "Failed to install dependencies"
}

pixi_install() {
  has_cmd pixi || {
    echo "pixi is not installed. Installing pixi."
    curl -fsSL https://pixi.sh/install.sh | sh
    has_cmd pixi || die "Failed to install pixi"
  }

  pixi global install bash-language-server bat bottom carapace direnv duf eza \
    fd fzf gdu gh go-gum go-shfmt imagemagick jq just lazygit mask nushell xh \
    ripgrep shellcheck tealdeer tectonic television tmuxp trash-cli yazi \
    zoxide starship
}

main() {
  export PATH="$HOME/.pixi/bin:$PATH"
  has_cmd dnf || die "only fedora supported. Quitting."

  system_install
  pixi_install
  dotfiles_install
  nu "${DOT_DIR}/setup.nu" fish config
}

main "$@"
