#!/usr/bin/env bash

set -euo pipefail

has_cmd() {
  command -v "$1" >/dev/null 2>&1
}

die() {
  printf "ERROR: %s\n" "$*" >&2
  exit 1
}

dotfiles_clone() {
  readonly REPO_URL="https://github.com/pervezfunctor/fedora-nix-niri-config.git"
  readonly DOT_DIR="$HOME/.local/share/fedora-nix-niri-config"

  [ -d "$DOT_DIR" ] || {
    echo "Cloning dotfiles to $DOT_DIR."
    git clone "$REPO_URL" "$DOT_DIR" || die "Failed to clone $REPO_URL"
    return
  }

  [ -z "$(git -C "$DOT_DIR" status --porcelain)" ] && {
    echo "Dotfiles repo clean. Pulling latest changes"
    git -C "$DOT_DIR" pull --rebase || {
      echo "Rebase failed. Aborting."
      git -C "$DOT_DIR" rebase --abort || die "Failed to abort rebase"
    }
  }
}

main() {
  export PATH="$HOME/.pixi/bin:$PATH"
  has_cmd dnf || die "Only fedora supported."

  sudo dnf update -y || die "Failed to update packages"
  sudo dnf install -y curl git fish || die "Failed to install dependencies"

  has_cmd pixi || {
    echo "pixi is not installed. Installing pixi."
    curl -fsSL https://pixi.sh/install.sh | sh
    has_cmd pixi || die "Failed to install pixi"
  }
  pixi global install nushell trash-cli starship || die "Failed to install pixi packages"

  has_cmd nu || die "Failed to install nushell"
  dotfiles_clone
  nu "$DOT_DIR/setup.nu" fish config
}

main "$@"
